"""Insert test data for testing"""
from database.db import get_db_context
from database.models import Vehicle, Source, VehicleType, FuelType, Transmission
from datetime import datetime

test_vehicles = [
    {
        "source": Source.OLX,
        "source_id": "test1",
        "url": "https://olx.pt/test1",
        "vehicle_type": VehicleType.CAR,
        "brand": "Volkswagen",
        "model": "Golf",
        "year": 2018,
        "km": 45000,
        "price": 12000.0,
        "location": "Lisboa",
        "title": "Volkswagen Golf 1.6 TDI",
        "description": "Carro em excelente estado, revisões na marca",
        "images": ["https://example.com/img1.jpg"],
        "fuel_type": FuelType.DIESEL,
        "transmission": Transmission.MANUAL,
        "horsepower": 110,
        "engine_size": 1598,
    },
    {
        "source": Source.STANDVIRTUAL,
        "source_id": "test2",
        "url": "https://standvirtual.com/test2",
        "vehicle_type": VehicleType.CAR,
        "brand": "BMW",
        "model": "Série 3",
        "year": 2019,
        "km": 35000,
        "price": 25000.0,
        "location": "Porto",
        "title": "BMW 320i M Sport",
        "description": "Primeiro dono, livro de revisões",
        "images": ["https://example.com/img2.jpg"],
        "fuel_type": FuelType.GASOLINE,
        "transmission": Transmission.AUTOMATIC,
        "horsepower": 184,
        "engine_size": 1998,
    },
    {
        "source": Source.AUTOSAPO,
        "source_id": "test3",
        "url": "https://autos.sapo.pt/test3",
        "vehicle_type": VehicleType.CAR,
        "brand": "Mercedes",
        "model": "Classe A",
        "year": 2020,
        "km": 25000,
        "price": 22000.0,
        "location": "Braga",
        "title": "Mercedes A200 AMG Line",
        "description": "Garantia Mercedes, pneus novos",
        "images": ["https://example.com/img3.jpg"],
        "fuel_type": FuelType.GASOLINE,
        "transmission": Transmission.AUTOMATIC,
        "horsepower": 163,
        "engine_size": 1597,
    },
    {
        "source": Source.OLX,
        "source_id": "test4",
        "url": "https://olx.pt/test4",
        "vehicle_type": VehicleType.CAR,
        "brand": "Renault",
        "model": "Megane",
        "year": 2017,
        "km": 65000,
        "price": 9500.0,
        "location": "Lisboa",
        "title": "Renault Megane 1.5 dCi",
        "description": "Carro bem cuidado, pneus novos",
        "images": ["https://example.com/img4.jpg"],
        "fuel_type": FuelType.DIESEL,
        "transmission": Transmission.MANUAL,
        "horsepower": 110,
        "engine_size": 1461,
    },
    {
        "source": Source.STANDVIRTUAL,
        "source_id": "test5",
        "url": "https://standvirtual.com/test5",
        "vehicle_type": VehicleType.CAR,
        "brand": "Peugeot",
        "model": "308",
        "year": 2019,
        "km": 30000,
        "price": 14500.0,
        "location": "Faro",
        "title": "Peugeot 308 1.2 PureTech",
        "description": "Primeiro dono, garantia",
        "images": ["https://example.com/img5.jpg"],
        "fuel_type": FuelType.GASOLINE,
        "transmission": Transmission.MANUAL,
        "horsepower": 130,
        "engine_size": 1199,
    },
    {
        "source": Source.AUTOSAPO,
        "source_id": "test6",
        "url": "https://autos.sapo.pt/test6",
        "vehicle_type": VehicleType.CAR,
        "brand": "Audi",
        "model": "A4",
        "year": 2018,
        "km": 55000,
        "price": 21000.0,
        "location": "Coimbra",
        "title": "Audi A4 2.0 TDI",
        "description": "Carro impecável, revisões na marca",
        "images": ["https://example.com/img6.jpg"],
        "fuel_type": FuelType.DIESEL,
        "transmission": Transmission.AUTOMATIC,
        "horsepower": 150,
        "engine_size": 1968,
    },
    {
        "source": Source.OLX,
        "source_id": "test7",
        "url": "https://olx.pt/test7",
        "vehicle_type": VehicleType.CAR,
        "brand": "Toyota",
        "model": "Corolla",
        "year": 2020,
        "km": 20000,
        "price": 18000.0,
        "location": "Lisboa",
        "title": "Toyota Corolla 1.8 Hybrid",
        "description": "Híbrido, muito económico",
        "images": ["https://example.com/img7.jpg"],
        "fuel_type": FuelType.HYBRID,
        "transmission": Transmission.AUTOMATIC,
        "horsepower": 122,
        "engine_size": 1798,
    },
    {
        "source": Source.STANDVIRTUAL,
        "source_id": "test8",
        "url": "https://standvirtual.com/test8",
        "vehicle_type": VehicleType.CAR,
        "brand": "Ford",
        "model": "Focus",
        "year": 2017,
        "km": 70000,
        "price": 8500.0,
        "location": "Porto",
        "title": "Ford Focus 1.5 TDCi",
        "description": "Bom estado geral",
        "images": ["https://example.com/img8.jpg"],
        "fuel_type": FuelType.DIESEL,
        "transmission": Transmission.MANUAL,
        "horsepower": 120,
        "engine_size": 1499,
    },
    {
        "source": Source.AUTOSAPO,
        "source_id": "test9",
        "url": "https://autos.sapo.pt/test9",
        "vehicle_type": VehicleType.CAR,
        "brand": "Seat",
        "model": "Leon",
        "year": 2019,
        "km": 40000,
        "price": 13500.0,
        "location": "Setúbal",
        "title": "Seat Leon 1.5 TSI",
        "description": "FR, desportivo",
        "images": ["https://example.com/img9.jpg"],
        "fuel_type": FuelType.GASOLINE,
        "transmission": Transmission.MANUAL,
        "horsepower": 150,
        "engine_size": 1498,
    },
    {
        "source": Source.OLX,
        "source_id": "test10",
        "url": "https://olx.pt/test10",
        "vehicle_type": VehicleType.CAR,
        "brand": "Nissan",
        "model": "Qashqai",
        "year": 2018,
        "km": 50000,
        "price": 16000.0,
        "location": "Lisboa",
        "title": "Nissan Qashqai 1.5 dCi",
        "description": "SUV familiar, muito espaço",
        "images": ["https://example.com/img10.jpg"],
        "fuel_type": FuelType.DIESEL,
        "transmission": Transmission.MANUAL,
        "horsepower": 110,
        "engine_size": 1461,
    },
]

with get_db_context() as db:
    # Delete existing test data
    db.query(Vehicle).filter(Vehicle.source_id.like("test%")).delete()
    db.commit()
    
    # Insert new test data
    for data in test_vehicles:
        vehicle = Vehicle(**data)
        db.add(vehicle)
    
    db.commit()
    print(f"Inserted {len(test_vehicles)} test vehicles")
