"""Add market value factors

Revision ID: 8727b491756e
Revises: 923fb2cd1402
Create Date: 2026-05-01 14:12:52.200760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8727b491756e'
down_revision: Union[str, None] = '923fb2cd1402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('is_national', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('num_owners', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('condition_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'condition_status')
    op.drop_column('vehicles', 'warranty_months')
    op.drop_column('vehicles', 'num_owners')
    op.drop_column('vehicles', 'is_national')
    # ### end Alembic commands ###
