"""Add IA features

Revision ID: 923fb2cd1402
Revises: 
Create Date: 2026-04-17 01:22:42.585840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923fb2cd1402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_reviews', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_ai_reviews_is_active'), 'ai_reviews', ['is_active'], unique=False)
    op.add_column('vehicles', sa.Column('valuation_details', sa.JSON(), nullable=True))
    op.add_column('vehicles', sa.Column('trim_level', sa.String(length=200), nullable=True))
    op.add_column('vehicles', sa.Column('has_damage', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('maintenance_history', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('aesthetic_score', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('fuel_type', sa.Enum('GASOLINE', 'DIESEL', 'ELECTRIC', 'HYBRID', 'GPL', 'GAS', name='fueltype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'fuel_type')
    op.drop_column('vehicles', 'aesthetic_score')
    op.drop_column('vehicles', 'maintenance_history')
    op.drop_column('vehicles', 'has_damage')
    op.drop_column('vehicles', 'trim_level')
    op.drop_column('vehicles', 'valuation_details')
    op.drop_index(op.f('ix_ai_reviews_is_active'), table_name='ai_reviews')
    op.drop_column('ai_reviews', 'is_active')
    # ### end Alembic commands ###
